/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  SfMap as SfMap
} from './components/sf-map/sf-map';

declare global {
  interface HTMLSfMapElement extends SfMap, HTMLElement {
  }
  var HTMLSfMapElement: {
    prototype: HTMLSfMapElement;
    new (): HTMLSfMapElement;
  };
  interface HTMLElementTagNameMap {
    "sf-map": HTMLSfMapElement;
  }
  interface ElementTagNameMap {
    "sf-map": HTMLSfMapElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "sf-map": JSXElements.SfMapAttributes;
    }
  }
  namespace JSXElements {
    export interface SfMapAttributes extends HTMLAttributes {
      
        longitude?: string,
        latitude?: string,
        radius?: string
    }
  }
}

